version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: "${DATABASE_NAME}"
      PG_DATA: /var/lib/postgresql/data
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data: